#+TITLE: Préservation du fibré normal par déformation
#+AUTHOR: 
#+DATE:
#+LATEX_CLASS: dip
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \DeclareMathOperator\Ii{\mathcal{I}}
#+LATEX_HEADER: \DeclareMathOperator\rk{rk}
#+LATEX_HEADER: \DeclareMathOperator{\zzb}{\zeta\bar\zeta}
#+LATEX_HEADER: \DeclareMathOperator{\II}{\mathbb{I}}
#+LATEX_HEADER: \DeclareMathOperator{\VVv}{\mathcal{V}}
#+LATEX_HEADER: \newtheorem{prop}{Proposition}
#+LATEX_HEADER: \newtheorem{cor}{Corollaire}
#+LATEX_HEADER: \newtheorem{lem}{Lemme}
#+LATEX_HEADER: \DeclareMathOperator{\cycles}{Cycles}
#+LATEX_HEADER: \DeclareMathOperator{\Sec}{Sec}
#+LATEX_HEADER: \DeclareMathOperator\uu{\underline{u}}
#+LATEX_HEADER: \hypersetup{colorlinks=true, linkcolor=DarkBlue}
#+LATEX_HEADER: \geometry{a4paper,left=9em,right=9em,top=8em,bottom=7em}
# #+LATEX_HEADER: \usepackage[inline]{showlabels}
# +LATEX_HEADER: \numberwithin{equation}{subsection}
#+options: num:3
#+TODO: TODO ONGOING | DONE

#+STARTUP: indent
# +FILETAGS:

* Notations
Soit $Z$ une variété complexe, $(L(t))_{\in \Delta}$ un famille de déformations de $L = L(0)$.

On recouvre $Z$ par des ouverts $Z_a$ de trace $L_a$ sur $L$. On peut supposer que $Z_a$ est un polydique de $\C^n$ avec coordonnées $(v_a,w_a)$ et $L_a$ est défini par l'équation $w_a = 0$. Les $v_a$ sont alors des coordonnées locales sur $L$.

Quitte à restreindre $\Delta$, on peut supposer que $L(t)$ a pour équation
\[
w_a = \varphi_a(v_a,t)
\]
dans $Z_a$. Les $v_a$ sont donc également des coordonnées locales sur $L(t)$.

On se donne les changements de carte de $Z$ sous la forme
\begin{align}
v_b &= f_{ba}(v_a,w_a)\\
w_b &= g_{ba}(v_a,w_a)
\end{align}

En particulier, les changements de carte de $L$ sont donnés par
\[
v_b = f_{ba}(v_a,0)
\]
et ceux de $L(t)$ par
\[
v_b = f_{ba}(v_a,\varphi_a(v_a,t))
\]

* Fibré normal
Toujours sur l'hypothèse de petitesse de $\Delta$, les coordonnées $w_a$ sont des coordonnées locales sur $Z$ transverses à tous les $L(t)$.

Leurs changements de carte au dessus d'un point de coordonnée $v_a$ de $L$ est donné par la relation
\[
w_b = g_{ba}(v_a,w_a)
\]

Ainsi les cocycles de Cech $\epsilon_{ba}(v,t)$ qui définissent les changements de trivialisation du fibré normal de $L(t)$ dans $Z$ sont donnés par
\[
\epsilon_{ba}(v_a,t) = \dpp{g_{ba}}{w}(v_a,\varphi(v_a,t))
\]

On veut construire un isomorphisme entre le fibré normal à $L(t)$ et le fibré normal à $L$. Pour cela il suffit de relier $\epsilon_\bullet(t)$ et $\epsilon_\bullet(0)$ par un cobord, plus précisément, on cherche à résoudre
\begin{equation}
\label{cobord}
\epsilon_{ba}(v_a,t)\alpha_a(v_a,t) = \alpha_b(v_b,t)\epsilon_{ba}(v_b,0)
\end{equation}
d'inconnue $\alpha_\bullet(v,t)$ matrice inversible.

* Développement en série entière

À l'ordre $0$ en $t$ la relation \eqref{cobord} nous donne
$\alpha_\bullet(v,0) = \Id$.

À l'ordre $1$, on trouve
\[
(\partial_t\epsilon_{ba})(v_a,0) + \epsilon_{ba}(v_a,0)(\partial_t \alpha_a)(v_a,0)  = (\partial_t \alpha_b)(v_b,0)\epsilon_{ba}(v_a,0)
\]
ou encore
\[
(\partial_t \alpha_b)(v_b,0) = (\partial_t \alpha_a)(v_a,0) + \epsilon_{ba}(v_a,0)^{-1}(\partial_t\epsilon_{ba})(v_a,0)
\]

À l'ordre $k$, avec la notation des indices implicites
\[
(\partial^k_t \alpha_b) = (\partial^k_t \alpha_a) + \epsilon_{ba}^{-1}\left(
k \partial^{k-1}_t \alpha_a\partial_t \epsilon_{ba} + \cdots  + \partial^k_t\epsilon_{ba}\right)
\] 
où tout est évalué en $(v,0)$.

On peut imposer $\alpha_{0}(v,t) = \Id$ pour tout $v,t$ et par connexité, la relation précédente définie entièrement $\alpha_\bullet$ sur $L \times \Delta$.

* Convergence

On voudrait une propriété du genre, pour tout $t \in \Delta$ et pour tout $a$, pour tout $v = v_a \in L_a$
\[
\alpha_a(v,t) \ll A(t)
\]
où
\[
A(t) = \dfrac{\lambda}{16\chi}\sum_{s \geq 1} \dfrac{\chi}{s^2}(t_1 + \cdots + t_{4n})^s = \sum_{\uu \in \N^{4n}} A_{\uu} t^{\uu}
\]


- Le fait d'avoir $t$ de dimension $4n$ ... est perturbant, ce n'est pas ce que je cherchais à faire au début. D'autre part c'est peut-être la meilleur chose à faire pour avoir uniformité de la convergence dans toutes les directions.

En dim $1$ ((réelle ou complexe ?))
\[
A(t) = \dfrac{\lambda}{16} \sum_{s \geq 1} \dfrac{t^s}{s^2}
\]
qui a un rayon de convergence de $1$.
Et $u(t) \ll v(t)$ signifie que tous les coefficients de $u$ sont majorés en valeur absolue par les coefficients de $v$ (positifs).


